return {
	by_mod = {
		my_castle_doors = 'my_doors',
		my_cottage_doors = 'my_doors',
		my_default_doors = 'my_doors',
		my_fancy_doors = 'my_doors',
		my_future_doors = 'my_doors',
		my_garage_door = 'my_doors',
		my_hidden_doors = 'my_doors',
		my_misc_doors = 'my_doors',
		my_old_doors = 'my_doors',
		my_saloon_doors = 'my_doors',
		my_sliding_doors = 'my_doors',

		mesecons_alias = 'mesecons',
		mesecons_blinkyplant = 'mesecons',
		mesecons_button = 'mesecons',
		mesecons_commandblock = 'mesecons',
		mesecons_delayer = 'mesecons',
		mesecons_detector = 'mesecons',
		mesecons_doors = 'mesecons',
		mesecons_extrawires = 'mesecons',
		mesecons_fpga = 'mesecons',
		mesecons_gates = 'mesecons',
		mesecons_hydroturbine = 'mesecons',
		mesecons_insulated = 'mesecons',
		mesecons_lamp = 'mesecons',
		mesecons_lightstone = 'mesecons',
		mesecons_luacontroller = 'mesecons',
		mesecons_materials = 'mesecons',
		mesecons_microcontroller = 'mesecons',
		mesecons_movestones = 'mesecons',
		mesecons_mvps = 'mesecons',
		mesecons_noteblock = 'mesecons',
		mesecons_pistons = 'mesecons',
		mesecons_powerplant = 'mesecons',
		mesecons_pressureplates = 'mesecons',
		mesecons_random = 'mesecons',
		mesecons_receiver = 'mesecons',
		mesecons_solarpanel = 'mesecons',
		mesecons_stickyblocks = 'mesecons',
		mesecons_switch = 'mesecons',
		mesecons_torch = 'mesecons',
		mesecons_walllever = 'mesecons',
		mesecons_wires = 'mesecons',

		maidroid_core = 'maidroid',
		maidroid_tool = 'maidroid',

		["3d_armor"] = 'armor',
		shields = 'armor',
		armor_addon = 'armor',
		moarmour = 'armor',
	},
	by_group = {
		-- Order all stairs and slabs to the stairs group
		stair = 'stairs',
		slab = 'stairs',
	}
}
